// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xugctmihxywozkvpuubk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1Z2N0bWloeHl3b3prdnB1dWJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMzIyNjcsImV4cCI6MjA3NDcwODI2N30.30b3hFvtUHscVAe87cnIf5J3LNaXuG2aVbWXFCUOu7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});